//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/InputControls/CrosshairControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CrosshairControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CrosshairControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CrosshairControls"",
    ""maps"": [
        {
            ""name"": ""CrosshairMovement"",
            ""id"": ""e3014ab5-a370-4362-8563-c9f48d2666d1"",
            ""actions"": [
                {
                    ""name"": ""MouseMovement"",
                    ""type"": ""Value"",
                    ""id"": ""dfd8db6a-49b4-4bee-a259-1ec4e7eaa1f5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JoystickMovement"",
                    ""type"": ""Value"",
                    ""id"": ""902cff2a-4593-4bd2-b559-e5598f80e439"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4937ce96-4ae9-49d4-919c-8703e094c388"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6aba3f47-aa04-40cf-94e3-b21452131f2c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JoystickMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CrosshairMovement
        m_CrosshairMovement = asset.FindActionMap("CrosshairMovement", throwIfNotFound: true);
        m_CrosshairMovement_MouseMovement = m_CrosshairMovement.FindAction("MouseMovement", throwIfNotFound: true);
        m_CrosshairMovement_JoystickMovement = m_CrosshairMovement.FindAction("JoystickMovement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CrosshairMovement
    private readonly InputActionMap m_CrosshairMovement;
    private List<ICrosshairMovementActions> m_CrosshairMovementActionsCallbackInterfaces = new List<ICrosshairMovementActions>();
    private readonly InputAction m_CrosshairMovement_MouseMovement;
    private readonly InputAction m_CrosshairMovement_JoystickMovement;
    public struct CrosshairMovementActions
    {
        private @CrosshairControls m_Wrapper;
        public CrosshairMovementActions(@CrosshairControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseMovement => m_Wrapper.m_CrosshairMovement_MouseMovement;
        public InputAction @JoystickMovement => m_Wrapper.m_CrosshairMovement_JoystickMovement;
        public InputActionMap Get() { return m_Wrapper.m_CrosshairMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CrosshairMovementActions set) { return set.Get(); }
        public void AddCallbacks(ICrosshairMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_CrosshairMovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CrosshairMovementActionsCallbackInterfaces.Add(instance);
            @MouseMovement.started += instance.OnMouseMovement;
            @MouseMovement.performed += instance.OnMouseMovement;
            @MouseMovement.canceled += instance.OnMouseMovement;
            @JoystickMovement.started += instance.OnJoystickMovement;
            @JoystickMovement.performed += instance.OnJoystickMovement;
            @JoystickMovement.canceled += instance.OnJoystickMovement;
        }

        private void UnregisterCallbacks(ICrosshairMovementActions instance)
        {
            @MouseMovement.started -= instance.OnMouseMovement;
            @MouseMovement.performed -= instance.OnMouseMovement;
            @MouseMovement.canceled -= instance.OnMouseMovement;
            @JoystickMovement.started -= instance.OnJoystickMovement;
            @JoystickMovement.performed -= instance.OnJoystickMovement;
            @JoystickMovement.canceled -= instance.OnJoystickMovement;
        }

        public void RemoveCallbacks(ICrosshairMovementActions instance)
        {
            if (m_Wrapper.m_CrosshairMovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICrosshairMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_CrosshairMovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CrosshairMovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CrosshairMovementActions @CrosshairMovement => new CrosshairMovementActions(this);
    public interface ICrosshairMovementActions
    {
        void OnMouseMovement(InputAction.CallbackContext context);
        void OnJoystickMovement(InputAction.CallbackContext context);
    }
}
